name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
      with:
        node-version: '16.x'  # Specify the Node.js version you need
        always-auth: false
        architecture: 'x64'
        check-latest: true
        registry-url: 'https://registry.npmjs.org'
        scope: '@my-org'
        token: ${{ secrets.GITHUB_TOKEN }}
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
